### ISSUE TITLE
Unable to clone "git clone git@github.com:chesslablab/testing-redux-chess.git"

### ISSUE THREAD

**Issue by goutham03062001** [chesslablab/testing-redux-chess#3]
![image](https://user-images.githubusercontent.com/66135872/232547583-713e1736-e6e8-45af-9e77-26a0408785a7.png)

I'm getting this error. Please look into this and guide me through.

And it throws 

**Warning: Permanently added 'github.com' (ED25519) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.**

**Comment by programarivm** [comment]
It seems as though an [SSH key must be set up](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent) for authentication.
